# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "orchestration-demo"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "orchestration-demo"
path = "src/main.rs"

[dependencies]
sleet = { path = "../../../crates/sleet" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
chrono.workspace = true
async-trait.workspace = true
thiserror.workspace = true
