# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "talking-database-demo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "talking-database-demo"
path = "src/main.rs"

[dependencies]
stele = { workspace = true }
llm-contracts = { workspace = true }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio-test.workspace = true
