# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "gtr_core"
version.workspace = true
edition.workspace = true

[lib]
name = "gtr_core"
crate-type = ["cdylib", "rlib"]

# Features no longer needed; NIF code always compiled
[features]
default = []

[dependencies]
rustler = { workspace = true, features = ["serde"] }
serde = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }

# Workspace crates
steel = { path = "../../../../crates/steel", default-features = false, features = ["fabric_min"] }
