# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "ffi-demo"
version.workspace = true
edition.workspace = true
license = "AGPL-3.0"

[dependencies]
sleet = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
