[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    "RUSTSEC-2025-0012", # backoff unmaintained
    "RUSTSEC-2024-0384", # instant unmaintained
    "RUSTSEC-2024-0436", # paste unmaintained
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "BSL-1.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "Unlicense",
    "Zlib",
    "LicenseRef-UFL-1.0",
    "CC0-1.0",
    "EPL-2.0",
    "BUSL-1.1",
    "CDLA-Permissive-2.0",
    "OpenSSL",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["AGPL-3.0"], crate = "stele" },
    { allow = ["AGPL-3.0"], crate = "steel" },
    { allow = ["AGPL-3.0"], crate = "sleet" },
    { allow = ["AGPL-3.0"], crate = "estel" },
    { allow = ["AGPL-3.0"], crate = "llm-contracts" },
    { allow = ["AGPL-3.0"], crate = "utils" },
    { allow = ["AGPL-3.0"], crate = "protocols" },
    { allow = ["AGPL-3.0"], crate = "bytecode-vm-demo" },
    { allow = ["AGPL-3.0"], crate = "data-exchange-iam-demo" },
    { allow = ["AGPL-3.0"], crate = "flows-demo" },
    { allow = ["AGPL-3.0"], crate = "basic-database-demo" },
    { allow = ["AGPL-3.0"], crate = "talking-database-demo" },
    { allow = ["AGPL-3.0"], crate = "runtime-demo" },
    { allow = ["AGPL-3.0"], crate = "scribes-demo" },
    { allow = ["AGPL-3.0"], crate = "telegram-messaging-demo" },
    { allow = ["AGPL-3.0"], crate = "thinking-system" },
    { allow = ["AGPL-3.0"], crate = "orchestration-demo" },
    { allow = ["AGPL-3.0"], crate = "vm-demo" },
    { allow = ["AGPL-3.0"], crate = "sleet-demo" },
    { allow = ["AGPL-3.0"], crate = "estel-chart-demo" },
    { allow = ["AGPL-3.0"], crate = "agent-orchestration-demo" },
    { allow = ["AGPL-3.0"], crate = "ffi-demo" },
]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
