[package]
name = "kg-audit"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
stele = { workspace = true }
