# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "scribes-demo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stele = { workspace = true }
steel = { workspace = true }
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
surrealdb.workspace = true
dotenvy.workspace = true
serde.workspace = true
reqwest.workspace = true
async-trait.workspace = true
thiserror.workspace = true
clap.workspace = true
egui.workspace = true
eframe.workspace = true
tokio-util.workspace = true
serde_yaml.workspace = true
regex.workspace = true
md5.workspace = true

[[bin]]
name = "scribes-demo"
path = "src/main.rs"
