# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "thinking-system"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "thinking-system"
path = "src/main.rs"

[dependencies]
# Core architecture layers
steel = { workspace = true }
stele = { workspace = true }
sleet = { workspace = true }
estel = { workspace = true }

# Utility libraries
utils = { workspace = true }
protocols = { workspace = true }

# System dependencies
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
iroh = { workspace = true }
llm-contracts = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
config = { workspace = true }
tokio-stream = { workspace = true }
futures = { workspace = true }
surrealdb = { workspace = true }
regex = { workspace = true }
md5 = { workspace = true }
async-stream = "0.3"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls","json"] }
async-trait = { workspace = true }
clap = { workspace = true }
thinking-system-ui = { package = "thinking-system-ui", path = "ui" }
dotenvy = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
tempfile = { workspace = true }
