# SPDX-License-Identifier: AGPL-3.0-only

# Simplified NLU Processing Rules for Testing
# Single policy that always uses bundled extraction

policies:
  - name: canonicalize_first
    priority: 100
    description: "Prefer single-pass canonicalization"
    conditions: {}
    strategy:
      type: parallel
      actions:
        - task: canonicalize
          model_capability: full_extraction
          priority: 1
      stages: []

# Global settings
global_settings:
  max_parallel_tasks: 1
  timeout_seconds: 30
  enable_caching: false

# Task definitions - only keep what we need
tasks:
  canonicalize:
    description: "Single-pass canonical records extraction"
    required_capabilities:
      ["extraction", "reasoning", "full_extraction", "fast_extraction"]
