# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "flows-function-demo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "flows-function-demo"
path = "src/main.rs"

'thinkingsystem-workspace-hack' = []

[dependencies]
# Internal crates
stele = { workspace = true, default-features = false }
steel = { workspace = true }
llm-contracts = { workspace = true }

# External dependencies
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
tokio.workspace = true
dotenvy.workspace = true
uuid.workspace = true
evalexpr.workspace = true
chrono.workspace = true
regex.workspace = true
reqwest.workspace = true
async-trait.workspace = true
wat.workspace = true
wasmprinter.workspace = true
rand.workspace = true
libloading.workspace = true
tempfile.workspace = true

[features]
default = ["dynamic-native"]
dynamic-wasi = ["stele/dynamic-wasi"]
dynamic-native = ["stele/dynamic-native"]
dynamic-memo-api = [] # expose memo externs to generated code
dynamic-memo-auto = ["dynamic-memo-api"] # enable automatic regeneration with memo hint (instrumentation stub)
ui = ["dep:eframe", "dep:egui"]

[dependencies.egui]
workspace = true
optional = true

[dependencies.eframe]
workspace = true
optional = true
