# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "estel-chart-demo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
estel = { workspace = true, features = ["symbolic", "learned-scorer"] }
anyhow = { workspace = true }
chrono = { workspace = true }
csv = "1.3.1"
eframe = { workspace = true }
egui = { workspace = true }
env_logger = "0.11.8"
itertools = "0.14.0"
rayon = { workspace = true }
regex = { workspace = true }
rfd = "0.15.4"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dependencies.polars]
version = "0.49.1"
features = [
    "lazy",
    "csv",
    "parquet",
    "json",
    "strings",
    "temporal",
    "dtype-datetime",
    "dtype-date"
]
