# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "estel-chart-demo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
estel = { path = "../../../crates/estel", features = ["symbolic", "learned-scorer"] }
anyhow = "1.0.98"
chrono = "0.4.41"
csv = "1.3.1"
eframe = "0.32.0"
egui = "0.32.0"
env_logger = "0.11.8"
itertools = "0.14.0"
rayon = "1.10.0"
regex = "1.11.1"
rfd = "0.15.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
serde_yaml = "0.9.34"
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full"] }
uuid = "1.17.0"

[dependencies.polars]
version = "0.49.1"
features = [
    "lazy",
    "csv",
    "parquet",
    "json",
    "strings",
    "temporal",
    "dtype-datetime",
    "dtype-date"
]
