# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "agent-orchestration-demo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "agent-orchestration-demo"
path = "src/main.rs"

[dependencies]
# Internal crates
sleet = { path = "../../../crates/sleet" }
stele = { path = "../../../crates/stele" }

# External dependencies (using workspace deps where possible)
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
chrono = { version = "0.4", features = ["serde"] }
rand.workspace = true
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
