# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "sleet-demo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sleet = { path = "../../../crates/sleet" }
stele = { path = "../../../crates/stele" }
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1.47", features = ["full"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"

[lints]
