[package]
name = "quic-relay-demo"
version = "0.1.0"
edition = "2021"
authors = ["ThinkingSystem Demo"]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true }

# Use the iroh version already in the workspace
iroh = { workspace = true }

# STELE LLM adapter and contracts
stele = { workspace = true }
llm-contracts = { workspace = true }

# optionally use steel for shared types later (keep for future)
steel = { workspace = true }
